### ISSUE TITLE
Source is unavailable

### ISSUE THREAD

**Issue by ertanmantas** [imedias/macbook12-spi-driver#1]
https://github.com/PatrickVerner/macbook12-spi-driver source is unavailable.
I'm a linux and github beginner.
My notebook model is macbook 14,3 and my system Ubuntu 22.04.03 LTS
Is it possible to create a new repo for PatrickVerner's files?
Thank you.

**Comment by joberkel** [comment]
The best way to get linux support for macs is using https://github.com/t2linux (as we do)
